package com.example.spring.mysql.springmysql;

import java.util.List;

import org.apache.commons.logging.Log;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.spring.mysql.springmysql.model.User;

@Controller
@RequestMapping(path = "/demo")  // This means URL's start with /demo (after Application path)
public class MainController {
    
    @Autowired  // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path = "/addNewUser")
    public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String email) {
        User newUser = new User(name, email);
        try {
            userRepository.save(newUser);
        } catch(Exception e) {
            return "Error!";
        }
        return "Saved";
        
    }

    @GetMapping(path = "/getAllUsers")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
